### ISSUE TITLE
Word Document Feedback tracking issue

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/pae-code-spec#142]
@BaMikusi sent along editorial comments in a Word document. For transparency I'll post the comments here, and check off the item in this issue when they have been fixed.

- [ ] The archaic spelling “Plaine and Easie” is really odd – I always assumed this was somehow a reference to Morley’s Introduction but I don’t know if Brook spoke of this explicitly somewhere. In any case, readers might have the same question, so it would be good to have a sentence about this in the intro if we have the slightest clue.
- [ ] “that help to identify the musical work.”
 better with indefinite article: “a”
- [ ] “The present specifications seeks to establish”
 better in plural: “seek”

- [ ] “the present specification is an attempt to ["pave the cowpaths"](https://en.wiktionary.org/wiki/pave_the_cowpath);”
 Since there are still some notable changes as compared to V1, this statement should be softened with “largely”/”primarily”/”to a great extent an attempt…”

- [ ] “are dependent on the second indicator.” – since this is the first (and in fact only) occurrence of the word “indicator” in the entire text, I wonder if every reader should know what it refers to
- [ ] EXAMPLE 1
 the last example here is a “Neume G clef” – this is historically quite unimaginable, so better have a C or F clef with the neume notation

- [ ] “These characters MUST be followed by a list of [Note Names](https://plaine-and-easie.info/v2/#note-names) that indicate the altered notes.”
 This sounds awkward, so perhaps better: “These characters MUST be followed by a list of [Note Names](https://plaine-and-easie.info/v2/#note-names) to be altered accordingly.”

- [ ] “directly on the note”
 Perhaps better: “directly before the note”
- [ ] “a single n character MAY be supplied to indicate a natural key signature, i.e., C Major or A minor.”
 The “i.e.” explanation is odd, since the incipit could be modal or even atonal – better omit it, or if you really need the major-minor example, say “e.g.” instead of “i.e.”

- [ ] “It may be interpreted either as a completely natural key signature (i.e., C major) or it may indicate that a key signature was missing entirely from the original source.”
 Here, too, the reference to C major is out of place (“e.g.” could be okay here as well), and I would also omit “completely”, the meaning of which seems vague here

- [ ] “The presence of the n character can be used to explicitly mark a key signature with no sharps or flats.”
 Better omit the first 3 words, and simply say: “The n character can be…”

- [ ] “For neume notation, the key signature MUST be omitted.”
 Are you really sure there are no plainchant sources with key signature? (I have a vague memory that a single b occasionally occurs, and would ask an expert if that might make a difference.)

- [ ] EXAMPLE 2
 Here again the remarks “(key is D major or B minor)” and “(key is E-flat major or C minor)” could be omitted, to be on the safe side

- [ ] “For neume notation, the time signature MUST be omitted.”
 The wording seems somewhat odd in that “omitted” could also imply that there is actually a time signature in the source which we nonetheless have to omit. Perhaps phrase it from another angle, like “no time signature can be given” or (if you really need the MUST) perhaps “the time signature MUST remain unspecified”?

- [ ] “c/ ("alla breve", or 2/4)”
 The alla breve in fact corresponds to 2/2

- [ ] EXAMPLE 3
 The textual remarks to the c3 and c2 examples do not seem to follow from the explanations above (and there is also a typo in “Imerfect”)

- [ ] “Notes and rests are the most basic [logical unit](https://plaine-and-easie.info/v2/#dfn-logical-unit)”
 at the end “units” should be plural

- [ ] “characters that specify different attributes of a note or rest symbol.”
 Without “symbol” this would seem to make more sense to me
- [ ] “Ornaments alter the performance of a note, a rest, or groups thereof.”
 I still find it very odd to assume that a rest could have an ornament – this presumably hints at the fermata, but the fermata is really not an ornament (as the latter word is used as a rule, and we should not divert from the general usage this far). I understand that, in the context of PAE, in 4.4.2 the fermata is listed under 4.4 Ornaments, but that should also be somehow amended – perhaps call 4.4 in general “Ornamental attributes” or the like? That way I could imagine the fermata standing there, while under “Ornaments” I cannot.
- [ ] “for example, a beam will contain two or more notes, or tuplet may be composed of two or more chords.”
 add an “a” before “tuplet”

- [ ] “The only time a space MAY occur is to separate a change of Clef, Key Signature, or Time Signature.”
 While I understand why MAY has been used here, I definitely find this wording much more confusing than having a MUST in its place.

- [ ] “extending the duration of the note by half again the indicated duration value.”
 “again” was perhaps supposed to be “against” here?

- [ ] “This character MUST be appended to the duration value.”
 Perhaps say “directly appended”? I know that’s a bit odd, but I have in fact seen quite a few old incipits in which the cataloger apparently wanted to use the dot for a value not explicitly stated but rather “inherited” from an earlier duration statement (like: 4EF.G8F), so perhaps we should have a clear statement about this approach being unacceptable. 

- [ ] “Multiple dots MAY be used, with each successive dot indicating that the duration is extended by half again.”
 This sounds a bit vague, so perhaps: “that the duration is extended again, by half of the value of the first dot.”

- [ ] “All letters MUST be uppercase; lowercase letters MUST NOT be used.”
 Perhaps add “in this context” at the end?

- [ ] “If the octave is omitted, the last specified octave indication is used for all following notes.”
 To be more precise, at the end I would add: “until a new octave is indicated.”

- [ ] “An [encoding](https://encoding.spec.whatwg.org/#encoding) MAY omit all duration indications. If no duration is supplied on any note, all notes are assumed to have a duration value of 4 (quarter note / crochet / semiminim).”
 AND
 “An encoding MAY omit all octave indications. If no octave is supplied on any note, all notes are assumed to be in octave C4. 2
 Both these appear to suggest as if this default behavior would only apply if there are no duration/octave indications at all in the entire incipit, so it would be better to talk only about the beginning of the incipit, since the default will really apply there (and of course remains valid if there are no statements later on, either, to overwrite it). So, perhaps simply say: “If at the beginning no duration/octave is supplied, the notes are assumed to have…”
 (NB: A later statement along the same lines seems okay: “If no duration is supplied in the [encoding](https://encoding.spec.whatwg.org/#encoding) a default duration of 4 is assumed.”)

- [ ] EXAMPLE 6
 The first 3 remarks seem confusing (in the third better say “Octave indications” in place of “Octaves”)

- [ ] “the alteration of the accidental MUST be interpreted as an alteration of the pitch in the key signature.“
 Perhaps say instead of “in the key signature” rather “defined by the key signature”?

- [ ] “A note altered by an accidental SHOULD NOT be altered subsequent times within the same bar.”
 Could be misunderstood to say that you cannot have an E-flat and then an E-natural in the same bar, so perhaps insert “be altered the same way subsequent…”

- [ ] “Accidentals MUST be interpreted by their written value, and MUST NOT be interpreted by their values relative to each other.”
Somewhat vague, so perhaps better end with something like this: “…be interpreted by their values relative to a preceding accidental.”

- [ ] EXAMPLE 13
 The Notation and the Remarks seem confused with EXAMPLE 14

- [ ] “This character MUST be specified in the order given above;”
 This statement actually occurs twice (for acciaccatura and appoggiatura, respectively) but in both cases it seems unclear what the “above” refers to

- [ ] “Consecutive single acciaccatura SHOULD NOT occur.”
 Should better be in the plural – I guess in American English you can simply say “acciaccaturas”?

- [ ] “the lower-case character r MUST be the last character in the final note of the group.”
 instead of “in” rather “after”?

- [ ] “There MUST be more than one note in a appogiatura group.”
 Instead of “a” better “an”
 AND IN GENERAL: the correct spelling is “appoggiatura” (with double g) – please correct/unify it throughout the text

- [ ] In Figure 3: “Double bar line with repeat sign on the left and on the right”
 Instead of “sign” better “signs”

- [ ] EXAMPLE 17
 The “Code” column is inconsistent in giving the full code or only the bar line type in question
 Also, here the odd skips from B to C make no sense, so better add ‘‘ before the C to have a musically less weird scale.

- [ ] “an equal sign character =. This character MUST be followed by a non-negative integer indicating the number of measures for which this rest applies,“
 The wording “non-negative integer” might potentially allow for zero to be entered here, which would make no sense, so perhaps better say “positive integer”.

- [ ] “Measure rests MAY indicate the number of measures that are being skipped in the original source before the musical content being captured by the incipit, regardless of whether these measures in the original source contain musical content.”
- [ ] Have you taken this from some earlier guidelines? Using rests to skip measures that are otherwise not empty sounds really weird to me…
- [ ] EXAMPLE 19
 The Remark for both examples reads “Clef, key signature, and time signature changes”, but in fact there is no clef change in either example on the left.
 (And I would once again add ‘‘ before the final C in the first note example for it to make some musical sense.)

- [ ] “If one or notes or rests are repeated several times, a repeat group MAY be used.”
 The word “more” is missing after “or”

- [ ] “There MUST NOT be any other characters between the two bar lines.”
 Perhaps better: “between these two bar lines.”

- [ ] “Measure repeats SHOULD NOT be used with Mensural notation.”
 Here, too, we should add (as above after a similar statement): “, due to the general absence of measures in this system of notation.”

- [ ] “Following the version declaration, the line MUST contain with a declaration of the clef.”
 Instead of “contain” perhaps “continue”?
